# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='weight')),
            ],
            options={
                'verbose_name': 'amount',
                'verbose_name_plural': 'amounts',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company|name')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('user', models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Food|name')),
                ('nameSV', models.CharField(max_length=100, verbose_name='Food|nameSV')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='food|description')),
                ('descriptionSV', models.CharField(blank=True, max_length=1000, verbose_name='food|descriptionSV')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='link')),
                ('extra', models.CharField(blank=True, max_length=1000, verbose_name='extra')),
                ('energy', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='energy')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fat')),
                ('saturatedFat', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='saturatedFat')),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='carbohydrate')),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sugar')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fiber')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='protein')),
                ('salt', models.DecimalField(decimal_places=10, default=0, max_digits=12, verbose_name='salt')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product|name')),
                ('nameSV', models.CharField(max_length=100, verbose_name='Product|nameSV')),
                ('weight', models.IntegerField(blank=True, default=0, verbose_name='weight')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='selosteet.Company', verbose_name='company')),
                ('ingredients', models.ManyToManyField(related_name='sisus', through='selosteet.Amount', to='selosteet.Food')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='amount',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selosteet.Food', verbose_name='food'),
        ),
        migrations.AddField(
            model_name='amount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selosteet.Product'),
        ),
    ]
